"use strict";

const utils = require("../utils");
const path = require("path");
const fs = require("fs-promise");
const dot = require("dot");

module.exports = class ServiceBase {

  constructor(config) {
    this.config = config || this.constructor.defaults();
  }

  bindEnvironment(env) {
    this.env = env;
  }

  configure() {
    if (!this._configure) {
      return Promise.resolve();
    }

    console.log("\n-- Configure " + this.ann("label"));
    return this._configure();
  }

  compose(containerType, services, envConfig) {
    let fnName = "compose_" + containerType;

    if (typeof this[fnName] !== "function") {
      utils.mustImplement(this, fnName);
    }

    return this[fnName](services, envConfig);
  }

  _getConfigFileInfo() {
    return null;
  }

  addConfigFiles(root) {
    let promises = [];
    let fileInfo = this._getConfigFileInfo();

    if (typeof fileInfo !== "object") {
      throw new Error(`Wrong config files data provided service ${this.ann("id")}`);
    }

    for (let [filename, data] of Object.entries(fileInfo)) {
      const confPath = path.join(__dirname, "services", this.ann("id"), "config", filename);
      const destPath = path.join(root, "config", this.ann("id"));

      let promise = fs.ensureDir(destPath);

      if (filename.match(/\.dot$/)) {
        promise = promise
          .then(() => {
            return this._compileConfigFile(confPath, data);
          })
          .then((configContent) => {
            return fs.writeFile(path.join(destPath, filename.substr(0, -".dot".length)), configContent);
          });
      }
      else {
        promise = promise.then(() => {
          return fs.copy(confPath, path.join(destPath, filename));
        });
      }

      promises.push(promise);
    }

    return Promise.all(promises);
  }


  _compileConfigFile(templatePath, data) {
    return fs.readFile(templatePath)
      .then((template) => {
        template = "# <drup autogenerated>\n\n" + template;

        dot.templateSettings.strip = false;
        dot.templateSettings.varname = "env";

        return dot.template(template)(data);
      })
      .catch((err) => {
        throw new Error(`Failed compiling config template:\nTEMPLATE:${templatePath}\n` + err);
      });
  }

  static defaults() {
    return {};
  }

};
