FROM php:{{= env.PHP_VERSION }}-fpm-alpine
MAINTAINER zoltan.fodor@pitechnologies.ro

RUN apk upgrade --update \
    && NPROC=$(getconf _NPROCESSORS_ONLN) \

{{/* Install any additional php extensions. */}}
{{? env.PHP_EXTENSIONS.length }}
    {{/* GD library dependencies */}}
    {{? env.PHP_EXTENSIONS.indexOf("gd") !== -1 }}
        && apk add \
            coreutils \
            freetype-dev \
            libjpeg-turbo-dev \
            libltdl \
            libmcrypt-dev \
            libpng-dev \
    {{?}}
    && docker-php-ext-install -j$NPROC {{= env.PHP_EXTENSIONS.join(" ") }} \
{{?}}

{{/* If so install xdebug and configure it. */}}
{{? env.PHP_XDEBUG }}
    && apk add autoconf make gcc g++ \
    && pecl install xdebug \
    && docker-php-ext-enable xdebug \
    && apk del autoconf make gcc g++ \
{{?}}